# DC schema
 
# --- !Ups

CREATE TABLE PROJECT (
    ID SERIAL NOT NULL PRIMARY KEY,
    NAME varchar(255) NOT NULL
);

CREATE TABLE TASK (
    ID SERIAL NOT NULL PRIMARY KEY,
    COLOR varchar(255) NOT NULL,
    STATUS varchar(255) NOT NULL,
    PROJECT integer NOT NULL REFERENCES PROJECT (ID)
);

# --- !Downs

DROP TABLE TASK;
DROP TABLE PROJECT;
